[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "cutters"
classifiers=[
    "Natural Language :: Croatian",
    "Natural Language :: English",
    "Topic :: Text Processing",
]
